version: "3.8"
services:
  mobile-react:
    build:
      dockerfile: Dockerfile.dev
      context: "."
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true